### ISSUE TITLE
tutorial issue

### ISSUE THREAD

**Issue by LJS-Student** [GraphSCI/GraphSCI#2]
I want to reproduce your methods but 
```
Error in mde(x) : cannot coerce type 'S4' to vector of type 'integer
```

this error occurred and I feel it's because of the below dropout object. 

```
dropout    <- assays(sim)$Dropout
mode(dropout) <- 'integer'
dropout <- as.data.frame(dropout)
```

Can you help me to solve this problem???

Thank you for your great research.

**Comment by GraphSCI** [comment]
These simulation codes come from https://github.com/theislab/dca/blob/master/scripts/simulate.R.
This error may be related to your environment or version.
